/** VBA enum constants shared by runtime registration and static analysis. */
export const VBA_ENUM_CONSTANTS = {
    VbCallType: {
        vbmethod: 1,
        vbget: 2,
        vblet: 4,
        vbset: 8,
    },
    VbCompareMethod: {
        vbbinarycompare: 0,
        vbtextcompare: 1,
        vbdatabasecompare: 2,
        vbusesystem: 0,
    },
    VbVarType: {
        vbempty: 0,
        vbnull: 1,
        vbinteger: 2,
        vblong: 3,
        vbsingle: 4,
        vbdouble: 5,
        vbcurrency: 6,
        vbdate: 7,
        vbstring: 8,
        vbobject: 9,
        vberror: 10,
        vbboolean: 11,
        vbvariant: 12,
        vbdataobject: 13,
        vbdecimal: 14,
        vbbyte: 17,
        vblonglong: 20,
        vbuserdefinedtype: 36,
        vbarray: 8192,
    },
    VbDayOfWeek: {
        vbsunday: 1,
        vbmonday: 2,
        vbtuesday: 3,
        vbwednesday: 4,
        vbthursday: 5,
        vbfriday: 6,
        vbsaturday: 7,
    },
    VbFirstWeekOfYear: {
        vbfirstjan1: 1,
        vbfirstfourdays: 2,
        vbfirstfullweek: 3,
    },
    VbFileAttribute: {
        vbnormal: 0,
        vbreadonly: 1,
        vbhidden: 2,
        vbsystem: 4,
        vbvolume: 8,
        vbdirectory: 16,
        vbarchive: 32,
        vbalias: 64,
    },
    VbTriState: {
        vbtristateusedefault: -2,
        vbtristatetrue: -1,
        vbtristatefalse: 0,
        vbtristateusefault: 2,
        vbusedefault: -2,
        vbusecompatible: 0,
    },
    VbStrConv: {
        vbuppercase: 1,
        vblowercase: 2,
        vbpropercase: 3,
        vbwide: 4,
        vbnarrow: 8,
        vbkatakana: 16,
        vbhiragana: 32,
        vbunicode: 64,
        vbfromunicode: 128,
    },
    VbMsgBoxStyle: {
        vbokonly: 0,
        vbokcancel: 1,
        vbabortretryignore: 2,
        vbyesnocancel: 3,
        vbyesno: 4,
        vbretrycancel: 5,
        vbcritical: 16,
        vbquestion: 32,
        vbexclamation: 48,
        vbinformation: 64,
        vbdefaultbutton1: 0,
        vbdefaultbutton2: 256,
        vbdefaultbutton3: 512,
        vbdefaultbutton4: 768,
        vbapplicationmodal: 0,
        vbsystemmodal: 4096,
    },
    VbMsgBoxResult: {
        vbok: 1,
        vbcancel: 2,
        vbabort: 3,
        vbretry: 4,
        vbignore: 5,
        vbyes: 6,
        vbno: 7,
    },
    VbError: {
        vbobjecterror: -2147221504,
    },
} as const;

export const VBA_ENUM_CONSTANT_NAMES = Object.fromEntries(
    Object.entries(VBA_ENUM_CONSTANTS).map(([typeName, values]) => [
        typeName,
        new Set(Object.keys(values)),
    ]),
) as unknown as { [K in keyof typeof VBA_ENUM_CONSTANTS]: ReadonlySet<string> };
